spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/linkupdb
    username : root
    password : qkrxotjd0505@
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.learningcrew.linkup


#jwt:
#  secret: Msrwyz/2xzZm0CkoRTWAg+9clCPiJVk5o+SUIKaImAJN539XmXe88IyrRnRTeO3amDO9ik4gM3kTHpTcl41S9A==
#  expiration: 1800000 # 30? ?????(access token)
#  refresh-expiration: 604800000 # 7?(refresh token)


springdoc:
  packages-to-scan: com.learningcrew.linkup
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8


image:
  image-dir: C:/Users/Playdata/Desktop/image
  image-url : http://localhost:8080/prductimgs/